CREATE TABLE [dbo].[ALGORITM$TYPE_ACTIVITY] (
    [id]     INT           IDENTITY (1, 1) NOT NULL,
    [text]   VARCHAR (150) NULL,
    [number] INT           NULL,
    CONSTRAINT [PK_ALGORITM$TYPE_ACTIVITY] PRIMARY KEY CLUSTERED ([id] ASC)
);

