CREATE TABLE [dbo].[ALGORITM$FUNCTION_BLOCKS] (
    [id]   INT           IDENTITY (1, 1) NOT NULL,
    [text] VARCHAR (250) NULL,
    CONSTRAINT [PK_ALGORITM$FUNCTION_BLOCKS] PRIMARY KEY CLUSTERED ([id] ASC)
);

