CREATE TABLE [dbo].[CLINIC23STUFF_FEEDBACK_CATEGORIES] (
    [id]      INT          IDENTITY (1, 1) NOT NULL,
    [date_in] DATETIME     CONSTRAINT [DF_CLINIC23STUFF_FEEDBACK_CATEGORIES_date_in] DEFAULT (getdate()) NULL,
    [user_in] VARCHAR (50) NULL,
    [guid]    VARCHAR (50) CONSTRAINT [DF_CLINIC23STUFF_FEEDBACK_CATEGORIES_guid] DEFAULT (newid()) NULL,
    [text]    VARCHAR (50) NULL,
    [del]     TINYINT      CONSTRAINT [DF_CLINIC23STUFF_FEEDBACK_CATEGORIES_del] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_CLINIC23STUFF_FEEDBACK_CATEGORIES] PRIMARY KEY CLUSTERED ([id] ASC)
);

