CREATE TABLE [dbo].[DISPLAY_DOCTROS_SERVER_LOG] (
    [id]      INT            IDENTITY (1, 1) NOT NULL,
    [date_in] DATETIME       CONSTRAINT [DF_DISPLAY_DOCTROS_SERVER_LOG_date_in] DEFAULT (getdate()) NULL,
    [text]    VARCHAR (2048) NULL,
    CONSTRAINT [PK_DISPLAY_DOCTROS_SERVER_LOG] PRIMARY KEY CLUSTERED ([id] ASC)
);

