CREATE TABLE [dbo].[DOGOVORS$REG_HISTORY] (
    [id]               INT           NOT NULL,
    [date_in]          DATETIME      CONSTRAINT [DF_DOGOVORS$REG_HISTORY_date_in] DEFAULT (getdate()) NULL,
    [guid]             VARCHAR (50)  CONSTRAINT [DF_DOGOVORS$REG_HISTORY_guid] DEFAULT (newid()) NULL,
    [user_in]          VARCHAR (50)  NULL,
    [number_storage]   VARCHAR (MAX) NULL,
    [date_reg]         DATETIME      NULL,
    [set_numb_automat] INT           CONSTRAINT [DF_DOGOVORS$REG_HISTORY_numb_hand] DEFAULT ((0)) NULL,
    [r_number]         VARCHAR (MAX) NULL,
    [r_date]           DATETIME      NULL,
    [idm_partner]      INT           NULL,
    [idm_dog_type]     INT           NULL,
    [subject]          VARCHAR (MAX) NULL,
    [cost_no_nds]      VARCHAR (50)  NULL,
    [cost_nds_value]   VARCHAR (50)  NULL,
    [cost_summ]        VARCHAR (50)  NULL,
    [r_date_deadline]  DATETIME      NULL,
    [idm_empl]         INT           NULL,
    [notes_conflicts]  VARCHAR (MAX) NULL,
    [notes_agreement]  VARCHAR (MAX) NULL,
    [notes]            VARCHAR (MAX) NULL,
    [idm_owner]        INT           NULL,
    [status]           INT           CONSTRAINT [DF_DOGOVORS$REG_HISTORY_status] DEFAULT ((1)) NULL,
    [idm_template]     INT           NULL,
    [pay_rules]        VARCHAR (MAX) NULL,
    [date_deadline]    DATETIME      NULL,
    [some_status]      INT           NULL,
    [curator_sended]   INT           CONSTRAINT [DF_DOGOVORS$REG_HISTORY_curator_sended] DEFAULT ((0)) NULL,
    [idm_isp]          INT           NULL,
    [isp_sended]       INT           NULL,
    [old_dogovor]      INT           CONSTRAINT [DF_DOGOVORS$REG_HISTORY_old_dogovor] DEFAULT ((0)) NULL,
    [idm_parent]       INT           NULL,
    [del]              TINYINT       CONSTRAINT [DF_DOGOVORS$REG_HISTORY_del] DEFAULT ((0)) NULL,
    [user_del]         VARCHAR (50)  NULL,
    [date_del]         DATETIME      NULL,
    [comment_clearNum] VARCHAR (MAX) NULL,
    [user_clear]       VARCHAR (50)  NULL,
    [date_clear]       DATETIME      NULL,
    [parent_dog]       INT           NULL
);

