CREATE TABLE [dbo].[EUROLAB$STOCK_DISCONTS] (
    [id]      INT           IDENTITY (1, 1) NOT NULL,
    [imgLink] VARCHAR (250) NULL,
    [link]    VARCHAR (250) NULL,
    [disable] INT           CONSTRAINT [DF_EUROLAB$STOCK_DISCONTS_disable] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_EUROLAB$STOCK_DISCONTS] PRIMARY KEY CLUSTERED ([id] ASC)
);

