CREATE TABLE [dbo].[GARAGE$ANDROID_GUID_SPR] (
    [id]   INT          IDENTITY (1, 1) NOT NULL,
    [text] VARCHAR (50) NULL,
    [guid] VARCHAR (50) NULL,
    CONSTRAINT [PK_GARAGE$ANDROID_GUID_SPR] PRIMARY KEY CLUSTERED ([id] ASC)
);

