CREATE TABLE [dbo].[KAD$WORK_TIME_MISSED_NUMCOM] (
    [id]             INT           IDENTITY (1, 1) NOT NULL,
    [date_in]        DATETIME      CONSTRAINT [DF_KAD$WORK_TIME_MISSED_NUMCOM_date_in] DEFAULT (getdate()) NULL,
    [numcom]         INT           NULL,
    [deadline]       DATETIME      CONSTRAINT [DF_KAD$WORK_TIME_MISSED_NUMCOM_deadline] DEFAULT (getdate()+(15)) NULL,
    [del]            INT           CONSTRAINT [DF_KAD$WORK_TIME_MISSED_NUMCOM_del] DEFAULT ((0)) NULL,
    [idm_empl]       INT           NULL,
    [idm_empl_bolid] INT           NULL,
    [DeviceTime]     DATETIME      NULL,
    [detalies]       VARCHAR (MAX) NULL,
    CONSTRAINT [PK_KAD$WORK_TIME_MISSED_NUMCOM] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_KAD$WORK_TIME_MISSED_NUMCOM_4]
    ON [dbo].[KAD$WORK_TIME_MISSED_NUMCOM]([numcom] DESC);


GO
CREATE NONCLUSTERED INDEX [IX_KAD$WORK_TIME_MISSED_NUMCOM_3]
    ON [dbo].[KAD$WORK_TIME_MISSED_NUMCOM]([idm_empl] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_KAD$WORK_TIME_MISSED_NUMCOM_2]
    ON [dbo].[KAD$WORK_TIME_MISSED_NUMCOM]([idm_empl_bolid] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_KAD$WORK_TIME_MISSED_NUMCOM_1]
    ON [dbo].[KAD$WORK_TIME_MISSED_NUMCOM]([del] ASC, [deadline] DESC);


GO
CREATE NONCLUSTERED INDEX [IX_KAD$WORK_TIME_MISSED_NUMCOM]
    ON [dbo].[KAD$WORK_TIME_MISSED_NUMCOM]([deadline] DESC);

