CREATE TABLE [dbo].[KAD$PSY_TEST_DOWNLOAD_HISTORY] (
    [id]        INT          IDENTITY (1, 1) NOT NULL,
    [user_in]   VARCHAR (50) NULL,
    [date_in]   DATETIME     CONSTRAINT [DF_KAD$PSY_TEST_DOWNLOAD_HISTORY_date_in] DEFAULT (getdate()) NULL,
    [ip_in]     VARCHAR (50) NULL,
    [idm_psy]   INT          NULL,
    [file_guid] VARCHAR (50) NULL,
    CONSTRAINT [PK_KAD$PSY_TEST_DOWNLOAD_HISTORY] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20200710-094616]
    ON [dbo].[KAD$PSY_TEST_DOWNLOAD_HISTORY]([idm_psy] ASC);

