CREATE TABLE [dbo].[KAD$EMPLOYEE_HISTORY] (
    [id]                     INT           NOT NULL,
    [date_in]                DATETIME      CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_date_in] DEFAULT (getdate()) NULL,
    [user_in]                VARCHAR (50)  NULL,
    [fam]                    VARCHAR (150) NULL,
    [name]                   VARCHAR (150) NULL,
    [otch]                   VARCHAR (150) NULL,
    [data_b]                 DATETIME      NULL,
    [idm_doljn]              INT           NULL,
    [idm_otdel]              INT           NULL,
    [idm_org]                INT           NULL,
    [status]                 INT           NULL,
    [phone_mob]              VARCHAR (50)  NULL,
    [phone_vn]               VARCHAR (50)  NULL,
    [phone_gor]              VARCHAR (50)  NULL,
    [login_ad]               VARCHAR (50)  NULL,
    [login_1c_t]             VARCHAR (50)  NULL,
    [login_1c_id]            VARCHAR (50)  NULL,
    [bolid_card_num]         VARCHAR (50)  NULL,
    [bolid_card_id]          INT           NULL,
    [email]                  VARCHAR (50)  NULL,
    [login_web]              VARCHAR (50)  NULL,
    [web_pass_sha256]        VARCHAR (70)  NULL,
    [idm_partner]            INT           NULL,
    [view_only_otdel]        INT           CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_view_only_otdel] DEFAULT ((0)) NULL,
    [view_only_self]         INT           CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_view_only_self] DEFAULT ((0)) NULL,
    [candidate]              TINYINT       CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_candidate] DEFAULT ((0)) NULL,
    [idm_controller]         INT           NULL,
    [actual]                 INT           CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_actual] DEFAULT ((1)) NULL,
    [idm_bolid]              INT           NULL,
    [photo_path]             VARCHAR (250) NULL,
    [noFilial]               INT           CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_noFilial] DEFAULT ((0)) NULL,
    [realId]                 INT           NULL,
    [wt_self_depart]         INT           CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_wt_self_depart] DEFAULT ((0)) NULL,
    [wt_hide]                INT           NULL,
    [wt_check_fact_only]     INT           CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_wt_check_fact_only] DEFAULT ((0)) NULL,
    [curator_dog]            INT           CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_curator_dog] DEFAULT ((0)) NULL,
    [call_center_worker]     INT           NULL,
    [IsLaborant]             INT           CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_IsLaborant] DEFAULT ((0)) NULL,
    [date_cur]               DATETIME      NULL,
    [user_cur]               VARCHAR (50)  NULL,
    [del]                    TINYINT       CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_del] DEFAULT ((0)) NULL,
    [guid]                   VARCHAR (50)  CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_guid] DEFAULT (newid()) NULL,
    [guid_web]               VARCHAR (50)  CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_guid_web] DEFAULT (newid()) NULL,
    [PinCode]                VARCHAR (10)  NULL,
    [auth_mobile_last_date]  DATETIME      NULL,
    [guid_iclinic]           VARCHAR (50)  NULL,
    [password_email]         VARCHAR (50)  NULL,
    [sms_only]               INT           CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_sms_only] DEFAULT ((0)) NULL,
    [date_dismissal]         DATETIME      NULL,
    [NotSendApplication]     TINYINT       NULL,
    [sertificate_date_expir] DATETIME      NULL,
    [ecp_status]             TINYINT       NULL,
    [ecp_date_expir]         DATETIME      NULL,
    [date_start_work]        DATETIME      NULL,
    [isKKB]                  BIT           CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_isKKB] DEFAULT ((0)) NULL,
    [wt_notsend]             BIT           CONSTRAINT [DF_KAD$EMPLOYEE_HISTORY_wt_notsend] DEFAULT ((0)) NULL,
    [standing]               INT           NULL,
    [idm_sert]               INT           NULL
);

