CREATE TABLE [dbo].[KAD$EMPLOYEE_AD_GROUPS] (
    [id]        INT           IDENTITY (1, 1) NOT NULL,
    [groupName] VARCHAR (150) NULL,
    [member]    VARCHAR (150) NULL,
    [domain]    VARCHAR (50)  NULL,
    [date_in]   DATETIME      CONSTRAINT [DF_KAD$EMPLOYEE_AD_GROUPS_date_in] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_KAD$EMPLOYEE_AD_GROUPS] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_KAD$EMPLOYEE_AD_GROUPS_2]
    ON [dbo].[KAD$EMPLOYEE_AD_GROUPS]([domain] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_KAD$EMPLOYEE_AD_GROUPS_1]
    ON [dbo].[KAD$EMPLOYEE_AD_GROUPS]([member] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_KAD$EMPLOYEE_AD_GROUPS]
    ON [dbo].[KAD$EMPLOYEE_AD_GROUPS]([groupName] ASC);

