CREATE TABLE [dbo].[NOMENCLATURE_AGREEMENT_AUTO_INSERT] (
    [id]       INT IDENTITY (1, 1) NOT NULL,
    [idm_empl] INT NULL,
    CONSTRAINT [PK_NOMENCLATURE_AGREEMENT_AUTO_INSERT] PRIMARY KEY CLUSTERED ([id] ASC)
);

