CREATE TABLE [dbo].[PBX$PHONE_VIP] (
    [id]    INT          IDENTITY (1, 1) NOT NULL,
    [phone] VARCHAR (20) NULL,
    CONSTRAINT [PK_PHONE_VIP] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_PHONE_VIP]
    ON [dbo].[PBX$PHONE_VIP]([id] ASC);

