CREATE TABLE [dbo].[RD$TASK_TEMPLATES] (
    [id]                INT             IDENTITY (1, 1) NOT NULL,
    [date_in]           DATETIME        CONSTRAINT [DF_RD$TASK_TEMPLATES_date_in] DEFAULT (getdate()) NULL,
    [user_in]           VARCHAR (50)    NULL,
    [tema]              VARCHAR (250)   NULL,
    [text]              VARCHAR (2000)  NULL,
    [status]            INT             NULL,
    [date_start]        DATETIME        NULL,
    [date_stop]         DATETIME        NULL,
    [day_stop]          SMALLINT        NULL,
    [date_fact_stop]    DATETIME        NULL,
    [vazhnost]          TINYINT         CONSTRAINT [DF_RD$TASK_TEMPLATES_vazhnost] DEFAULT ((2)) NULL,
    [del]               TINYINT         CONSTRAINT [DF_RD$TASK_TEMPLATES_del] DEFAULT ((0)) NOT NULL,
    [idm_isp]           INT             NULL,
    [idm_kontrol]       INT             NULL,
    [idm_project]       INT             NULL,
    [idm_task]          INT             NULL,
    [cost]              NUMERIC (18, 2) NULL,
    [cost_fact]         NUMERIC (18, 2) NULL,
    [idm_author]        INT             NULL,
    [guid]              VARCHAR (50)    CONSTRAINT [DF_RD$TASK_TEMPLATES_guid] DEFAULT (newid()) NULL,
    [idm_departments]   INT             NULL,
    [idm_otdel]         INT             NULL,
    [user_cor]          VARCHAR (50)    NULL,
    [date_cor]          DATETIME        NULL,
    [idm_algoritm_step] INT             NULL,
    [idm_task_init]     INT             NULL,
    [inform_send]       INT             CONSTRAINT [DF_RD$TASK_TEMPLATES_inform_send] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_RD$TASK_TEMPLATES] PRIMARY KEY CLUSTERED ([id] ASC)
);

