CREATE TABLE [dbo].[RM$OS$BILLING_HISTORY] (
    [id]                  INT             NOT NULL,
    [user_in]             VARCHAR (50)    NULL,
    [date_in]             DATETIME        CONSTRAINT [DF_RM$OS$BILLING_HISTORY_date_in] DEFAULT (getdate()) NULL,
    [date_bill]           DATETIME        NULL,
    [number]              VARCHAR (50)    NULL,
    [idm_partner]         INT             NULL,
    [idm_owner]           INT             NULL,
    [idm_isp]             INT             NULL,
    [idm_curator]         INT             NULL,
    [description]         VARCHAR (MAX)   NULL,
    [summ]                DECIMAL (18, 2) NULL,
    [summ_cy]             DECIMAL (18, 2) NULL,
    [summ_cy_type]        INT             NULL,
    [cy_rate]             FLOAT (53)      NULL,
    [percent_cy]          FLOAT (53)      NULL,
    [nds]                 DECIMAL (18, 2) NULL,
    [status]              INT             NULL,
    [idm_billing]         INT             NULL,
    [date_paid]           DATETIME        NULL,
    [nom_paid]            VARCHAR (50)    NULL,
    [send_assept]         INT             CONSTRAINT [DF_RM$OS$BILLING_HISTORY_send_assept] DEFAULT ((0)) NULL,
    [idm_department]      INT             NULL,
    [invoice_number]      VARCHAR (50)    NULL,
    [invoice_date]        DATETIME        NULL,
    [idm_dogovor]         INT             NULL,
    [bill_dogovor]        INT             NULL,
    [type_pay]            INT             NULL,
    [date_pay]            DATETIME        NULL,
    [date_pay_purpose]    DATETIME        NULL,
    [assept_number]       INT             NULL,
    [assept_date]         DATETIME        NULL,
    [assept_idm]          INT             NULL,
    [idm_budgetGroup]     INT             NULL,
    [idm_budget]          INT             NULL,
    [send_agree]          INT             CONSTRAINT [DF_RM$OS$BILLING_HISTORY_send_agree] DEFAULT ((0)) NULL,
    [idm_file_store]      INT             NULL,
    [user_cur]            VARCHAR (50)    NULL,
    [date_cur]            DATETIME        NULL,
    [del]                 INT             CONSTRAINT [DF_RM$OS$BILLING_HISTORY_del] DEFAULT ((0)) NULL,
    [bill_guid]           VARCHAR (50)    NULL,
    [AllowAgreeMarceting] INT             CONSTRAINT [DF_RM$OS$BILLING_HISTORY_AllowAgreeMarceting] DEFAULT ((0)) NULL,
    [budget_depart]       INT             NULL,
    [budget_month]        DATETIME        NULL,
    [pay_oms]             BIT             NULL,
    [IsNewStatus]         BIT             NULL,
    [IsNotDogovor]        BIT             NULL
);

