CREATE TABLE [dbo].[RM$OS_HISTORY] (
    [id]                  INT            NULL,
    [date_in]             DATETIME       CONSTRAINT [DF_RM$OS_HISTORY_date_in] DEFAULT (getdate()) NULL,
    [user_in]             VARCHAR (50)   NULL,
    [idm_org]             INT            NULL,
    [idm_type]            INT            NULL,
    [idm_addr]            INT            NULL,
    [idm_mol]             INT            NULL,
    [place]               VARCHAR (50)   NULL,
    [text]                VARCHAR (1024) NULL,
    [date_start]          DATETIME       NULL,
    [serial_num]          VARCHAR (50)   NULL,
    [inv_num]             VARCHAR (50)   NULL,
    [doc_date_purchase]   DATETIME       NULL,
    [doc_num_purchase]    VARCHAR (50)   NULL,
    [cash_date]           DATETIME       NULL,
    [cash_number]         VARCHAR (50)   NULL,
    [receip_date]         DATETIME       NULL,
    [receip_number]       VARCHAR (50)   NULL,
    [idm_partner]         INT            NULL,
    [del]                 TINYINT        CONSTRAINT [DF_RM$OS_HISTORY_del] DEFAULT ((0)) NULL,
    [idm_invoice]         INT            NULL,
    [status]              INT            NULL,
    [idm_partner_service] INT            NULL,
    [inv_num_extended]    VARCHAR (50)   NULL,
    [idm_head_org]        INT            NULL,
    [idm_otdel]           INT            NULL,
    [idm_responsible]     INT            NULL,
    [user_cor]            VARCHAR (50)   NULL,
    [date_cor]            DATETIME       NULL,
    [date_release]        SMALLINT       NULL,
    [date_expired]        DATE           NULL,
    [date_check]          DATE           NULL,
    [idm_priority]        INT            NULL,
    [idm_billing]         INT            NULL,
    [idm_depart_offices]  INT            NULL,
    [guid]                VARCHAR (50)   CONSTRAINT [DF_RM$OS_HISTORY_guid] DEFAULT (newid()) NULL
);

