CREATE TABLE [dbo].[SSMP$MAIN_HISTORY] (
    [id]                  INT            NULL,
    [user_in]             VARCHAR (50)   NULL,
    [date_in]             DATETIME       CONSTRAINT [DF_SSMP$MAIN_HISTORY_date_in] DEFAULT (getdate()) NULL,
    [count]               TINYINT        NULL,
    [fam]                 VARCHAR (50)   NULL,
    [name]                VARCHAR (50)   NULL,
    [otch]                VARCHAR (50)   NULL,
    [date_b]              DATETIME       NULL,
    [address]             VARCHAR (250)  NULL,
    [address_dop]         VARCHAR (1024) NULL,
    [phone_1]             VARCHAR (50)   NULL,
    [phone_2]             VARCHAR (50)   NULL,
    [calling_fio]         VARCHAR (100)  NULL,
    [symptoms]            VARCHAR (512)  NULL,
    [comment]             VARCHAR (512)  NULL,
    [idm_team]            INT            NULL,
    [idm_reg_1c]          VARCHAR (50)   NULL,
    [status]              SMALLINT       NULL,
    [del]                 TINYINT        NULL,
    [year]                SMALLINT       NULL,
    [result_t]            VARCHAR (512)  NULL,
    [date_end]            DATETIME       NULL,
    [phone_sys]           VARCHAR (20)   NULL,
    [dt_call]             DATETIME       NULL,
    [dt_departure]        DATETIME       NULL,
    [dt_service_start]    DATETIME       NULL,
    [dt_service_stop]     DATETIME       NULL,
    [guid]                VARCHAR (50)   NULL,
    [date_cor]            DATETIME       NULL,
    [paytype]             INT            NULL,
    [date_recive_team]    DATETIME       NULL,
    [control_time_out]    SMALLINT       NULL,
    [control_descr]       VARCHAR (1024) NULL,
    [user_cor]            VARCHAR (50)   NULL,
    [control_datetime]    DATETIME       NULL,
    [control_reaction]    DATETIME       NULL,
    [sms_sended]          INT            NULL,
    [date_brigade_start]  DATETIME       NULL,
    [mkb10_id]            INT            NULL,
    [help]                VARCHAR (MAX)  NULL,
    [date_brigade_end]    DATETIME       NULL,
    [date_car_start]      DATETIME       NULL,
    [date_car_stop]       DATETIME       NULL,
    [date_car_diff]       DATETIME       NULL,
    [date_car_time_to_go] DATETIME       NULL,
    [brigade_full]        VARCHAR (500)  NULL,
    [brigade_doctor]      VARCHAR (100)  NULL,
    [idm_insurance]       INT            NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_SSMP$MAIN_HISTORY]
    ON [dbo].[SSMP$MAIN_HISTORY]([id] ASC);

